version: "3"
services:
  mongodb:
    image: mongo
    ports:
      - "27018:27017" # host:container

  socialmediadashboard:
    build: .
    image: socialapp
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      PORT: 3000
      SECRET_KEY: "your_secret_key"
      MONGO_URL: "mongodb://mongodb:27017/mydb"
